# msa-rabbitmq PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: msa-rabbitmq-pvc
  labels:
    app: msa-rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
